spring.application.name=smartfieldoperations

spring.datasource.url=jdbc:postgresql://localhost:5432/site_visit_db
spring.datasource.username=postgres
spring.datasource.password=Shupe#77

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080