<%-- 
    Document   : summary
    Created on : 08 Mar 2024, 10:23:28 AM
    Author     : MemaniV
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Summary Page</title>
    </head>
    <body>
        <h1>Summary</h1>
        <%
            int cnt = (Integer)session.getAttribute("cnt");
            int tot = (Integer)session.getAttribute("tot");
            int cntNonPalindromes = (Integer)session.getAttribute("cntNonPalindromes");
            String computerName = (String)pageContext.getServletContext().getInitParameter("computer_name");
            String name = (String)session.getAttribute("name");
        %>
        <p>
            Hi <b><%=name%></b>. Below is the summary report generated by <b><%=computerName%></b>.
        </p>
        <table border="1">
            <tr>
                <td>How many numbers were checked? </b></td>
                <td><b><%=tot%></b></td>
            </tr>
            <tr>
                <td>How many were palindromes? </b></td>
                <td><b><%=cnt%></b></td>
            </tr>
            <tr>
                <td>How many were non-palindromes? </b></td>
                <td><b><%=cntNonPalindromes%></b></td>
            </tr>
        </table>
        <p>
            Please click <a href="EndSessionServlet.do">here</a> to 
            end the session.
        </p>
    </body>
</html>

